### ISSUE TITLE
demo priorities

### ISSUE THREAD

**Issue by ghost** [time-bank/favorbank#16]
dashboard screen priorities:

** "people you are helping" to-do: ** 

DONE -"sorry! something came up" button should trigger action to move item back to "active requests" list.

** "people helping you" to-do: ** 

DONE -"pay" button should trigger action to update account balances and remove item from list.

DONE -"cancel this request" should remove item from list.

**Comment by harvidson** [comment]
active requests:

DONE--let users commit to doing a favor


DONE -- hook up Daniel's new work to main site

DONE --acount balance to show

DONE -- trash can
DONE -- on YOUR REQUESTS: give name under requests with a volunteer

--
